source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'PGPCalendarView_Example', :exclusive => true do
  pod "PGPCalendarView", :path => "../"
end

target 'PGPCalendarView_Tests', :exclusive => true do
  pod "PGPCalendarView", :path => "../"

  
end
