source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

workspace "PGPCalendarView"

target 'PGPCalendarView_Example' do
  pod "PGPCalendarView", :path => "../"
end

target 'PGPXCalendarView' do
  project 'PGPXCalendarView/PGPXCalendarView'
  pod "PGPCalendarView", :path => "../"
end

target 'PGPCalendarView_Tests' do
  pod "PGPCalendarView", :path => "../"

  
end
